# Generated by Django 4.1.7 on 2023-10-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='sequence',
            field=models.PositiveSmallIntegerField(choices=[(1, 'First Image'), (2, 'Second Image'), (3, 'Third Image')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='job_type',
            field=models.CharField(choices=[('Field Repair', 'Field Repair'), ('Service Centre Repair', 'Service Centre Repair'), ('Installation', 'Installation')], default='Repair', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('job_card', 'sequence')},
        ),
    ]
