# Generated by Django 4.1.7 on 2023-07-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='closed_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
