# Generated by Django 4.1.7 on 2023-07-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_jobcard_closed_at_jobcard_closed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_type',
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='survey_completed',
            field=models.BooleanField(default=False),
        ),
    ]
