# Generated by Django 4.1.7 on 2023-07-23 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_remove_image_image_type_image_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcard',
            old_name='assigned_time',
            new_name='assigned_date',
        ),
        migrations.RenameField(
            model_name='jobcard',
            old_name='completed_time',
            new_name='completed_date',
        ),
        migrations.RemoveField(
            model_name='image',
            name='sequence',
        ),
    ]
