# Generated by Django 4.1.7 on 2023-08-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_rename_assigned_time_jobcard_assigned_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='additional_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='complaint_or_query',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='resolution',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='service_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='technician_assessment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='technician_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
