# Generated by Django 4.1.7 on 2023-08-13 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rma_number', models.CharField(blank=True, max_length=200, null=True)),
                ('service_centre', models.CharField(blank=True, choices=[('MRE Service Centre', 'MRE Service Centre'), ('Johannesburg Centre', 'Johannesburg Centre'), ('Durban Service Centre', 'Durban Service Centre'), ('Bloemfontein Service Centre', 'Bloemfontein Service Centre'), ('Cape Town Service Centre', 'Cape Town Service Centre'), ('Middelburg Service Centre', 'Middelburg Service Centre'), ('Polokwane Service Centre', 'Polokwane Service Centre')], max_length=200, null=True)),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=200, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('inv_no', models.CharField(blank=True, max_length=200, null=True)),
                ('inv_date', models.DateField(blank=True, null=True)),
                ('item_code', models.CharField(blank=True, max_length=200, null=True)),
                ('package_condition', models.CharField(blank=True, choices=[('Intact', 'Intact'), ('Damaged', 'Damaged'), ('Sealed', 'Sealed'), ('No Packaging', 'No Packaging')], max_length=200, null=True)),
                ('goods_condition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=200, null=True)),
                ('action', models.CharField(blank=True, choices=[('Repair', 'Repair'), ('Replace', 'Replace'), ('Refund', 'Refund')], max_length=10, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_signature', models.ImageField(blank=True, null=True, upload_to='')),
                ('received_at_warehouse', models.BooleanField(blank=True, default=False)),
                ('converted_or_closed', models.BooleanField(blank=True, default=False)),
                ('serial_no', models.OneToOneField(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.jobcard')),
            ],
        ),
    ]
