# Generated by Django 4.1.7 on 2023-08-12 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_rename_assigned_time_jobcard_assigned_date_and_more'),
        ('rma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rma',
            name='serial_no',
        ),
        migrations.AddField(
            model_name='rma',
            name='serial_no',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.jobcard'),
        ),
    ]
