# Generated by Django 4.1.7 on 2023-08-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rma',
            name='serial_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
