# Generated by Django 4.1.7 on 2023-08-13 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_rename_assigned_time_jobcard_assigned_date_and_more'),
        ('rma', '0002_remove_rma_serial_no_rma_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='rma',
            name='recieved_at_warehouse',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='rma',
            name='serial_no',
            field=models.OneToOneField(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.jobcard'),
        ),
    ]
