# Generated by Django 4.1.7 on 2023-08-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0003_rma_recieved_at_warehouse_alter_rma_serial_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rma',
            old_name='recieved_at_warehouse',
            new_name='converted_or_closed',
        ),
        migrations.AddField(
            model_name='rma',
            name='received_at_warehouse',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
