# Generated by Django 4.1.7 on 2023-07-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cell_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
