# Generated by Django 4.1.7 on 2023-08-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_cell_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Technical Admin', 'Technical Admin'), ('Field Technician', 'Field Technician'), ('Hub Controller', 'Hub Controller')], max_length=20, null=True),
        ),
    ]
