# Generated by Django 4.1.7 on 2023-08-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_ChatID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
