# Generated by Django 4.1.7 on 2023-10-14 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_image_sequence_alter_jobcard_job_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_jobcardhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('change_description', models.TextField()),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='system.jobcard')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
