# Generated by Django 4.1.7 on 2023-10-14 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_image_sequence_alter_jobcard_job_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0003_jobhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobcardhistory',
            name='change_details',
        ),
        migrations.AlterField(
            model_name='jobcardhistory',
            name='job_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='system.jobcard'),
        ),
        migrations.DeleteModel(
            name='JobHistory',
        ),
    ]
